### ISSUE TITLE
Extra slash in system.py functions

### ISSUE THREAD

**Issue by alvinc13** [aruba/pyaoscx#2]
get_chassis_info and get_product_info are giving 404 responses due to an extra '/' in the URI calls.

**Comment by alagoutte** [comment]
Good catch, do you plan to fix ?

**Comment by alvinc13** [comment]
@derekwangHPEAruba has fix incoming

**Comment by derekwangHPEAruba** [comment]
Fixed in commit [7bc31ed40dabba64486f3d5a6f378359b8297415](https://github.com/aruba/pyaoscx/commit/7bc31ed40dabba64486f3d5a6f378359b8297415)
